CREATE TABLE tasks (
    id SERIAL PRIMARY KEY,
    date_added DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    title VARCHAR(150) NOT NULL,
    body TEXT,
    is_archived BOOLEAN DEFAULT FALSE,
    category_id INTEGER
);

CREATE TABLE categories (
    id SERIAL PRIMARY KEY,
    date_added DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    title VARCHAR(150) NOT NULL,
    body TEXT,
    is_archived BOOLEAN DEFAULT FALSE
);
